# Bun configuration
[install]
# Install packages from npm by default
registry = "https://registry.npmjs.org/"

# Cache configuration
cache = true

# Packages to exclude from bundling
[install.scopes]

[test]
# Test configuration
preload = ["./src/setup-tests.ts"]

[build]
# Build configuration
sourcemap = "external"
target = "bun" 